### ISSUE TITLE
我的方案可行性如何？

### ISSUE THREAD

**Issue by da-liii** [man-pages-zh/wiki#2]
详见：https://github.com/man-pages-zh/wiki/wiki

@man-pages-zh/owners

**Comment by hosiet** [comment]
对于 coreutils 这种利用 help2man 生成 man 文档的情况，内容重合度很高，的确应当与上游协作，并且利用 po 文件；这一点没有问题。

不过这毕竟是少数；一般来讲只有 GNU 一套工具的 man 手册页是这样生成的。考虑如 Linux Man Pages Project （包括大部分Section2/3的内容）的手册页看起来大多是手写的；再如 git 系列的手册页都是 docbook 生成的，以及其它各类软件，可能有不同的生成方法。想问一下，这些情况能用上 po 文件吗？怎么用比较好？我对中间的 .a 那一步不太理解。

另外，我觉得由于不同软件包情况各不相同，以及工具的限制，不同的软件包应该采用不同的翻译策略。再例如 ronn 无法实现自定义缩进与列表（有序/无序列表）的多层嵌套，docbook 可以处理这些复杂情况（例如 cd.1P 中出现的）。

**Comment by da-liii** [comment]
非常同意你的看法。
1. 关于ronn还是docbook，现在还不确定应该用哪种格式作为中间格式(.a)。也可以自己定制一个? 可能需要综合考量一下工作量吧。如果手册页本身就是用docbook写的，那么直接翻译docbook就可以啦。OmegaT直接就有对docbook的支持。
2. 使用po的一个重要原因是方便翻译和计算机辅助翻译。不知道你对i18n了解多少？其实我的了解也不多，这个可以去咨询一下。

不知道你不了解的是哪个部分？

**Comment by hosiet** [comment]
我对 i18n 与计算机辅助翻译之前也没有接触过；看来咱们需要多查查资料。

docbook 需要向上游索取 XML 文件，因为随软件包分发的是 roff 文件。需要联系上游。

中间格式应该需要再考虑；docbook 的优势就是 XML 的优势，结构化可扩展，但是劣势也类似，是不直观；ronn 相对更直观一些。

**Comment by intetnet** [comment]
相信我，翻译的中间格式一定要选html。

翻译完之后生成中文html之后，之后不管是采用那种排版方式都很方便。因为html转md（ronn），xml（docbook）都非常容易实现。

cat（计算机辅助翻译，比如omegat）对html的支持非常好，man本身也支持html的导出，除了html之外我想不到还会有更好的方案。

不要用po，不要用a，小众的东西会排斥大多数人。

**Comment by da-liii** [comment]
Quote: 不要用po，不要用a，小众的东西会排斥大多数人。

a指代一种合理的中间格式。对于po，应该不会有排斥人的效果吧。使用OmegaT来翻译的话，导入到里面，就什么都一样了吧。另外我觉得会被po排斥的人本身就不会参与翻译吧。毕竟，翻译本身就是一件吃力不讨好的事情。斟酌字句是一方面，更多时候要动手验证，甚至应该看看源代码。

使用po的原因主要为了解决这种[缺陷](https://github.com/man-pages-zh/wiki/wiki/%E8%AE%A1%E7%AE%97%E6%9C%BA%E8%BE%85%E5%8A%A9%E7%BF%BB%E8%AF%91#%E8%A7%A3%E5%86%B3%E5%88%86%E5%8F%A5%E7%9A%84%E7%BC%BA%E9%99%B7)。另外不知道你们了解LaunchPad，Transifex这些翻译网站吗？他们用的就是po。其实译者完全是不用文本编辑器去看po文件的。里面就是一个个语句对:(源语言,目标语言)。

不过如果html转换起来比较方便的话，就不用用po了。

**Comment by da-liii** [comment]
在 2015年4月22日 下午11:39，Boyuan Yang notifications@github.com写道：

> 我对 i18n 与计算机辅助翻译之前也没有接触过；看来咱们需要多查查资料。
> 
> docbook 需要向上游索取 XML 文件，因为随软件包分发的是 roff 文件。需要联系上游。
> 
> 中间格式应该需要再考虑；docbook 的优势就是 XML 的优势，结构化可扩展，但是劣势也类似，是不直观；ronn 相对更直观一些。

我觉得你可能没有理解我的方案。中间格式不是给人看的，不需要考虑直观不直观的问题。

中间格式只要满足不丢失关键信息（完备性）就可以了。另外就是要考虑我们维护这样一套工具链的代码实现复杂度。

**Comment by intetnet** [comment]
既然是中间格式，那 man2po + po2man 有没有对应的工具，如果有，易用吗，需要额外下载东西或者使用不熟悉的命令吗？我们用什么都可以，但有些人可能根据自己的需要来翻译文档，应该多为他们考虑。而 html 直接使用 `man -H %f` 这样的原生命令就可以了，使用浏览器就可以打开了，非常易用。

还有，po2man 据我了解，并没有可以直接生成排版良好的中文手册的工具，实际上没有一种工具可以，因为中文手册是一定需要排版的，既然如此，你觉得我们在排版的时候是开着浏览器对着 html 排版（格式漂亮）还是打开文本编辑器对着 po (文本，没有格式，但有很多扰民的语言标记）好呢。

po 作为程序文档格式不错，但作为通用格式来看，没有优势。两权相害取其利，既然都有不足，为什么不选择不足少的呢，所以我强烈推荐 html 作为中间格式。

**Comment by da-liii** [comment]
@intetnet 在我的方案里面，翻译和排版是分离的。翻译的人专注与翻译就可以了。

**Comment by intetnet** [comment]
@sadhen 嗯，应该这样，不过人总是为自己工作的，我觉得最大的可能性是某人发现一篇文档没有翻译，就自己翻译了，这时他选择 po 的可能性非常小。
