### ISSUE TITLE
man2html

### ISSUE THREAD

**Issue by da-liii** [man-pages-zh/wiki#3]
这两天对现有的man2html做了一个调研：
1. `man2html-base`(in Debian) 感觉这个做的最好
2. `groff -Thtml -man man.1`，这个比较坑

现成的`man2html-base`可以研究一下，稍稍改动一下代码，用作`man2a`的一个参考。

**Comment by da-liii** [comment]
@man-pages-zh/owners 

刚刚对`man2html-base`做了一个quick hack。感觉已经可以使用了。代码见[man2html](https://github.com/sadhen/man2html)

**Comment by intetnet** [comment]
这个是 man 转换成 hmtl 吗？

man 原生支持转换 html，参考 man 的手册。
