### ISSUE TITLE
格式转换的工具：使用pandoc

### ISSUE THREAD

**Issue by da-liii** [man-pages-zh/wiki#4]
@intetnet @hosiet 
1. 优点
    + 语法丰富
    + 开发也比较活跃
    + 支持的格式比较多
2. 缺点
- haskell比较难学，难以定制源代码

用于现有的方案：
groff->html->markdown->翻译->zh_CN/markdown->groff

我已经做了一些尝试，感觉是一个不错的方案，工作量也比ronn小。个人对haskell也比较感兴趣。不过感觉不需要改pandoc的源码。

**Comment by hosiet** [comment]
总觉得工作量会很大。

groff 转 html 可以由 man 实现，不过生成的 HTML 不怎么样；对中文支持也比较奇怪，到处都是 &#12345;
的实体标记，不过这个不是重点。

HTML 转 markdown 能用 pandoc 较简单地实现吗？我的意思是这真的不需要改 pandoc 源码就能转换为 ronn 格式的
markdown 么？我不太了解 pandoc 的工作原理。

如果不特别要求 ronn 格式的 markdown 的话，看起来 pandoc 也有直接由普通 markdown 生成 groff
文档的方式，不知道效果怎么样。

**Comment by da-liii** [comment]
pandoc有自己特殊格式的markdown，不必要转换成ronn了。

经过测试，pandoc效果拔群。我已经打算先采用pandoc，先把lidaobing的manpages-zh里面的东西全部整理成po文件，作为以后翻译使用的语料库。下周一之前应该能搞定。

关于pandoc的使用，我会写wiki，也请 @hosiet @intetnet 帮忙改进。intetnet之前提到的html转markdown应该也是指使用pandoc吧，不知道有没有更好的？

**Comment by hosiet** [comment]
效果拔群的话真是极好的；期待早日有可以演示的完整流程出现。

我会考虑近期写一个处理已有 roff
文档的小脚本，目标是为80字符宽做优化，避免出现大量空白；这样写作和翻译时就不必担心换行问题了。目标是这几周内能有一个效果展示，初步支持由 ronn
生成的 roff 文档。后续再考虑处理更多 roff 语法。

**Comment by intetnet** [comment]
@sadhen html 转 markdown 的工具很多，我不推荐 pandoc，因为依赖太多了，我们也不需要里面的大多数功能。你可以试行一下。到时候反馈一下感想。

@hosiet 嗯，加油！我这周也会赶赶工，把完整的流程做出来。

@man-pages-zh/owners 我这边的方案是：`groff->html->翻译->zh_CN/html->zh_CN/ronn->groff`。
