### ISSUE TITLE
CAT：利用现有的文件

### ISSUE THREAD

**Issue by da-liii** [man-pages-zh/wiki#5]
`OmegaT`的一个重要的功能是句子的模糊匹配。从已经翻译好的语料库中，根据句子的相似度给出翻译的建议。

那么如何制作这样的语料库呢？我的方案是制作po文件（这周末的计划）。现在已经可以利用`man2html`，`pandoc`完成中间格式与groff格式的相互转换了。

```
man.1 --> man.1.md
zh_CN/man.1 -> zh_CN/man.1.md
```

只要从这两个文件制作po文件就可以了。不知道有什么比较好的现成的方案？

或者不用生成po，直接由OmegaT操作一下就可以了。这个不知道怎么做？

**Comment by da-liii** [comment]
@man-pages-zh/owners 

已经初步抽取出了语料库，请看这里：[manpages-zh的data目录](https://github.com/man-pages-zh/manpages-zh)

**Comment by intetnet** [comment]
模糊匹配需要的是记忆库，windows 下一些软件可以通过现有的对照文件快速生成记忆库， linux 下我还不清楚。不过记忆库文件都是纯文本的文件，语法很简单，作出生成一个记忆库工具不难。只是大批量转换有可能会遇到问题，有时候很多人不是对照翻译的，多一句或少一句都会造成对照错乱，这时记忆库也就不准确了。
