### ISSUE TITLE
重新利用已有的资源?

### ISSUE THREAD

**Issue by felixonmars** [man-pages-zh/wiki#6]
我知道的已有 man-pages-zh 项目主要有
- https://github.com/lidaobing/manpages-zh
- https://github.com/LCTT/man-pages

希望能够整合已有的力量, 避免重复劳动 :)

**Comment by hosiet** [comment]
是的，我们知道 CMPP 与 LCTT 以前的工作成果；

不过问题一是大部分已有工作时间较久远，内容多有变化且存在排版等问题，二是我们想寻找一套完整、比较自动化且使用比较简易的翻译手段，并不想直接写 roff
文档，应该说现在还在摸索阶段。

当然，前人的翻译肯定是有参考价值的，翻译时会综合参照现有英文版与曾经的翻译内容。

**Comment by intetnet** [comment]
@felixonmars  @hosiet 不会有重复的劳动的，我们使用机器翻译。你翻译的任何东西都会保存在记忆里，下次遇到相同的语句就直接替换了，翻译的越多，以后需要翻译的内容就越少，按我估计，一个月后哪怕像 bash 这样巨长的手册也能在一个小时内完成全部翻译。

所以我们不仅继承了以前的成果的总体，甚至连它每句话都继承了，我们站在巨人的肩膀上，并远远的超越了他们。

**Comment by HtwoO** [comment]
以前在 crowdin 给 shadowsocks 作翻译的时候，很多网站提供的候选词都是可以直接用的，但我发现 transifex 没有那么方便，不过也有可能我在 transifex 关注的项目需要翻译的都是比较长的条目。
