### ISSUE TITLE
已确定排版方案

### ISSUE THREAD

**Issue by da-liii** [man-pages-zh/wiki#8]
@intetnet 
昨天晚上排版的方案已经敲定。

打算给groff提交一个patch（已提交），因为已经有日本开发者做过groff的CJK支持，所以其实很容易。

大家如果想知道排版的效果，请在`/usr/share/groff/1.22.3/tmac`下面添加`zh_CN.tmac`。其内容参考[这个](https://savannah.gnu.org/bugs/?44941)。

因为man命令是通过manpath的路径上表示语言的目录名来确定语言的，所以直接在当前目录下`man ./man.1`是无法看到排版的效果的。你可以把你翻译好的手册页放到`$HOME/.local/man/zh_CN`下面，然后再观察排版效果。

比如`$HOME/.local/man/zh_CN/man1/man.1`可以通过命令`man $HOME/.local/man/zh_CN/man1/man.1`，也可以`man -L zh_CN.utf8 man`。

**Comment by intetnet** [comment]
好，我看了一下，虽然电脑上显示不出日文，但格式对了。不需要每行80列，那排版就很简单了。

感谢你的贡献啊！我静候佳音。

**Comment by da-liii** [comment]
我看你在TODO里面列了好多，我不知道你是否喜欢用po翻译。我觉得既然排版没问题了。只要保证质量，怎样翻译都可以。不过最好大家能够避免重复劳动。我没有很远大的目标，目前只想把coreutils搞定，所以coreutils部分就预留给我吧。

**Comment by intetnet** [comment]
哈哈，我用什么都可以啊，po 这个格式挺好，软件的汉化不都是用它嘛。我选择 html 主要是考虑到通用性，但是就像你说的，只要保证质量，怎样翻译都可以。

我目前主要在翻译一些专业软件，所以你负责搞定 coreutils 吧，到时候我直接把它拉到项目模块里面来。如果你需要记忆库的话，可以从 https://github.com/manpages-zh/Translate 这里找到。

**Comment by hosiet** [comment]
我尝试了一下，修改tmac或是使用 -L 参数都没有起作用；倒是直接把 tmac 中的命令嵌入 groff 文档能够显示效果。我想这种方式同样可以考虑，在 patch 被应用之前或者旧系统上能起到立竿见影的效果。

**Comment by da-liii** [comment]
@hosiet 之前写得不太对，这个最后敲定的方法：https://github.com/man-pages-zh/wiki/wiki

groff的下一个版本1.22.4发布后，排版就不是一个问题了。

**Comment by intetnet** [comment]
不错哦。

我最近在翻译 geda/gaf，感觉计算机辅助翻译真心不错。你的 po 源文件准备的怎么样，我想了解一下 po 的流程。

**Comment by da-liii** [comment]
https://github.com/man-pages-zh/coreutils-po

这个就是啊。上个星期就可以了啊。（这段时间学业繁忙）
